config/routes.rb
Rails.application.routes.draw do
  resources :eventos, only: [:index] do
    resources :reservas, only: [:new, :create]
  end
  root 'eventos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/evento.rb
class Evento < ApplicationRecord
  has_many :reservas
end

app/models/reserva.rb
class Reserva < ApplicationRecord
  belongs_to :evento

  validates :nombre, :correo, :curp, presence: true
  validates :correo, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  def index
    @eventos = Evento.all
  end
end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  def new
    @evento = Evento.find(params[:evento_id])
    @reserva = Reserva.new
  end

  def create
    @evento = Evento.find(params[:evento_id])
    @reserva = @evento.reservas.build(reserva_params)

    if @reserva.save
      ReservaMailer.confirmacion_reserva(@reserva).deliver_later
      redirect_to eventos_path, notice: "Reservación creada correctamente."
    else
      flash.now[:alert] = 'No se pudo crear la reserva. Por favor, agregue los datos correctamente.'
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def reserva_params
    params.require(:reserva).permit(:nombre, :correo, :curp)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/views/eventos/index.html.erb
<div class="container">
  <h1>Eventos Disponibles</h1>
  <div class="row mt-2">
    <% @eventos.each do |evento| %>
    <div class="col-md-4">
      <div class="card">
        <img src="<%= evento.imagen %>" class="card-img-top" alt="Imagen del evento">
        <div class="card-body">
          <h5 class="card-title"><%= evento.nombre %></h5>
          <p class="card-text"><%= evento.descripcion %></p>
          <p class="card-text">Fecha: <%= evento.fecha %></p>
          <%= link_to 'Registrarse', new_evento_reserva_path(evento), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <% end %>
    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdminEventos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css">

  </head>

  <body>
    <%= render 'shared/flash'%>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/reservas/_formulario_registro.erb
<%= form_with model: @reserva, url: evento_reservas_path(@evento), local: true, class: "bootstrap-form" do |f| %>
  <div class="form-group">
    <%= f.label :nombre %>
    <%= f.text_field :nombre, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :correo %>
    <%= f.email_field :correo, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :curp %>
    <%= f.text_field :curp, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Registrar', class: "btn btn-primary btn-sm mt-2" %>
  </div>
<% end %>

app/views/reservas/new.html.erb
<div class="container d-flex justify-content-center align-items-center">
  <div class="row">
    <div class="col-12 text-center">
      <center>
      <img src="<%= @evento.imagen %>" class="mt-3" style="width: 500px" alt="Imagen del evento">
      </center>
      <h5><%= @evento.nombre %></h5>
      <p><%= @evento.descripcion %></p>
      <p>Fecha: <%= @evento.fecha %></p>
    </div>
  </div>
</div>


<div class="container mt-3">
  <div class="d-flex justify-content-center">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
      Confirmar Registro
    </button>
  </div>
</div>


<!-- Modal container -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="myModalLabel">Registro</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'reservas/formulario_registro', reserva: @reserva %>
      </div>
    </div>
  </div>
</div>



app/views/shared/_flash.html.erb
<% if alert || notice %>
  <% color = alert ? 'bg-red-400' : 'bg-green-400' %>
  <div class="fixed top-0 inset-x-0 m-4 z-30 pointer-events-none">
    <div class="flex flex-col items-end space-y-4">
      <div data-controller="alert" data-alert-dismiss-after-value="3000" data-alert-show-class="translate-x-0 opacity-100" data-alert-hide-class="translate-x-full opacity-0" class="ease-in-out duration-500 max-w-sm w-full shadow-lg rounded px-4 py-3 relative <%= color %> text-white pointer-events-auto translate-x-0 opacity-100">
        <div class="p-2">
          <div class="flex items-start">
            <div class="ml-3 w-0 flex-1 pt-0.5">
              <p class="text-sm leading-5 font-medium">
                <%= alert || notice %>
              </p>
            </div>
            <div class="ml-4 flex-shrink-0 flex">
              <button data-action="alert#close" class="inline-flex text-white focus:outline-none focus:text-gray-300 transition ease-in-out duration-150">
                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>